language: node_js
node_js:
 - "8"
 - "10"
brancher:
  only:
   - "dev"
   - "tags"
   - "master"
install:
  - "yarn"
  - "yarn global add codecov"
script:
  - "npm run test && npm run cover"
  - "codecov"